src/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Task__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectTaskController.cls
public class ProjectTaskController {
    
    @AuraEnabled
    public static List<Project__c> getProjects(){
        return [SELECT Id,Name FROM Project__c];
    }
    
    @AuraEnabled
    public static List<Task__c> getTasksOfProject(String projectId){
        return [SELECT Id,Name,Start_Date__c,Due_Date__c,Stage__c,Description__c 
                FROM Task__c
                WHERE Project__c = :projectId];
    }  
    
    @AuraEnabled
    public static Task__c upsertTask(Task__c taskRec){
        upsert taskRec;
        return taskRec;
    }
    
    @AuraEnabled
    public static void markTasksAsCompleted(List<Task__c> tasks){
        update tasks;
    }
    
    @AuraEnabled
    public static void deleteTask(String taskId){
        delete new Task__c(id=taskId);
    }
    
}